In [78]:
import pandas as pd
import numpy as np
import tensorflow as tf
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from tensorflow.keras import layers,models

In [79]:
df=pd.read_csv('BostonHousing.csv')

In [80]:
df

,crim,zn,indus,chas,nox,rm,age,dis,rad,tax,ptratio,b,lstat,medv
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222,18.7,396.90,5.33,36.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,0.06263,0.0,11.93,0,0.573,6.593,69.1,2.4786,1,273,21.0,391.99,9.67,22.4
502,0.04527,0.0,11.93,0,0.573,6.120,76.7,2.2875,1,273,21.0,396.90,9.08,20.6
503,0.06076,0.0,11.93,0,0.573,6.976,91.0,2.1675,1,273,21.0,396.90,5.64,23.9
504,0.10959,0.0,11.93,0,0.573,6.794,89.3,2.3889,1,273,21.0,393.45,6.48,22.0
505,0.04741,0.0,11.93,0,0.573,6.030,80.8,2.5050,1,273,21.0,396.90,7.88,11.9

In [83]:
x = df.drop('medv',axis=1)

In [88]:
y = df['medv']

In [89]:
x

,crim,zn,indus,chas,nox,rm,age,dis,rad,tax,ptratio,b,lstat
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296,15.3,396.90,4.98
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242,17.8,396.90,9.14
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242,17.8,392.83,4.03
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222,18.7,394.63,2.94
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222,18.7,396.90,5.33
...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,0.06263,0.0,11.93,0,0.573,6.593,69.1,2.4786,1,273,21.0,391.99,9.67
502,0.04527,0.0,11.93,0,0.573,6.120,76.7,2.2875,1,273,21.0,396.90,9.08
503,0.06076,0.0,11.93,0,0.573,6.976,91.0,2.1675,1,273,21.0,396.90,5.64
504,0.10959,0.0,11.93,0,0.573,6.794,89.3,2.3889,1,273,21.0,393.45,6.48
505,0.04741,0.0,11.93,0,0.573,6.030,80.8,2.5050,1,273,21.0,396.90,7.88

In [90]:
y

0      24.0
1      21.6
2      34.7
3      33.4
4      36.2
       ...
501    22.4
502    20.6
503    23.9
504    22.0
505    11.9
Name: medv, Length: 506, dtype: float64

In [91]:
scaler = StandardScaler()
x = scaler.fit_transform(x)

In [92]:
x

array([[-0.41978194,  0.28482986, -1.2879095 , ..., -1.45900038,
         0.44105193, -1.0755623 ],
       [-0.41733926, -0.48772236, -0.59338101, ..., -0.30309415,
         0.44105193, -0.49243937],
       [-0.41734159, -0.48772236, -0.59338101, ..., -0.30309415,
         0.39642699, -1.2087274 ],
       ...,
       [-0.41344658, -0.48772236,  0.11573841, ...,  1.17646583,
         0.44105193, -0.98304761],
       [-0.40776407, -0.48772236,  0.11573841, ...,  1.17646583,
         0.4032249 , -0.86530163],
       [-0.41500016, -0.48772236,  0.11573841, ...,  1.17646583,
         0.44105193, -0.66905833]])

In [93]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.2,random_state=42)

In [94]:
model = models.Sequential()

In [100]:
model.add(layers.Dense(64,activation='relu',input_shape = (x_train.shape[1],)))
model.add(layers.Dense(32,activation='relu')),
model.add(layers.Dense(1))

In [101]:
model.compile(optimizer='adam',loss = 'mse')

In [102]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_4 (Dense)             (None, 64)                896

 dense_5 (Dense)             (None, 32)                2080

 dense_7 (Dense)             (None, 64)                2112

 dense_8 (Dense)             (None, 32)                2080

 dense_9 (Dense)             (None, 1)                 33

=================================================================
Total params: 7,201
Trainable params: 7,201
Non-trainable params: 0
_________________________________________________________________

In [109]:
model.fit(x_train,y_train,epochs= 100,batch_size=30,validation_split=0.05)

Epoch 1/100
13/13 [==============================] - 1s 19ms/step - loss: 588.6998 - val_loss: 480.6257
Epoch 2/100
13/13 [==============================] - 0s 7ms/step - loss: 509.1450 - val_loss: 364.9942
Epoch 3/100
13/13 [==============================] - 0s 8ms/step - loss: 338.7189 - val_loss: 149.4942
Epoch 4/100
13/13 [==============================] - 0s 7ms/step - loss: 136.5728 - val_loss: 63.0323
Epoch 5/100
13/13 [==============================] - 0s 8ms/step - loss: 80.7540 - val_loss: 59.3876
Epoch 6/100
13/13 [==============================] - 0s 8ms/step - loss: 44.9491 - val_loss: 50.0337
Epoch 7/100
13/13 [==============================] - 0s 8ms/step - loss: 28.8575 - val_loss: 45.4807
Epoch 8/100
13/13 [==============================] - 0s 7ms/step - loss: 22.5463 - val_loss: 48.4835
Epoch 9/100
13/13 [==============================] - 0s 7ms/step - loss: 19.1975 - val_loss: 46.6183
Epoch 10/100
13/13 [==============================] - 0s 7ms/step - loss: 17.5619 - val_loss: 47.2764
Epoch 11/100
13/13 [==============================] - 0s 7ms/step - loss: 16.1569 - val_loss: 44.3001
Epoch 12/100
13/13 [==============================] - 0s 7ms/step - loss: 15.1875 - val_loss: 43.7992
Epoch 13/100
13/13 [==============================] - 0s 6ms/step - loss: 14.4727 - val_loss: 41.5348
Epoch 14/100
13/13 [==============================] - 0s 7ms/step - loss: 14.1271 - val_loss: 41.4140
Epoch 15/100
13/13 [==============================] - 0s 7ms/step - loss: 13.3159 - val_loss: 40.4181
Epoch 16/100
13/13 [==============================] - 0s 6ms/step - loss: 13.1738 - val_loss: 40.3919
Epoch 17/100
13/13 [==============================] - 0s 6ms/step - loss: 12.4907 - val_loss: 37.9246
Epoch 18/100
13/13 [==============================] - 0s 6ms/step - loss: 11.9245 - val_loss: 39.2917
Epoch 19/100
13/13 [==============================] - 0s 6ms/step - loss: 11.6769 - val_loss: 39.0336
Epoch 20/100
13/13 [==============================] - 0s 6ms/step - loss: 11.2152 - val_loss: 36.4388
Epoch 21/100
13/13 [==============================] - 0s 6ms/step - loss: 11.2106 - val_loss: 34.9280
Epoch 22/100
13/13 [==============================] - 0s 6ms/step - loss: 10.5818 - val_loss: 33.3471
Epoch 23/100
13/13 [==============================] - 0s 7ms/step - loss: 10.3658 - val_loss: 35.4921
Epoch 24/100
13/13 [==============================] - 0s 7ms/step - loss: 10.1072 - val_loss: 33.3296
Epoch 25/100
13/13 [==============================] - 0s 7ms/step - loss: 10.0388 - val_loss: 31.7254
Epoch 26/100
13/13 [==============================] - 0s 6ms/step - loss: 9.6941 - val_loss: 31.9918
Epoch 27/100
13/13 [==============================] - 0s 6ms/step - loss: 9.4570 - val_loss: 35.5154
Epoch 28/100
13/13 [==============================] - 0s 5ms/step - loss: 9.2157 - val_loss: 32.2981
Epoch 29/100
13/13 [==============================] - 0s 5ms/step - loss: 9.0636 - val_loss: 32.1960
Epoch 30/100
13/13 [==============================] - 0s 5ms/step - loss: 9.4687 - val_loss: 30.1314
Epoch 31/100
13/13 [==============================] - 0s 6ms/step - loss: 9.1352 - val_loss: 30.2497
Epoch 32/100
13/13 [==============================] - 0s 6ms/step - loss: 8.8169 - val_loss: 28.9476
Epoch 33/100
13/13 [==============================] - 0s 6ms/step - loss: 8.3535 - val_loss: 28.7920
Epoch 34/100
13/13 [==============================] - 0s 6ms/step - loss: 8.2337 - val_loss: 28.1358
Epoch 35/100
13/13 [==============================] - 0s 8ms/step - loss: 8.0268 - val_loss: 27.9699
Epoch 36/100
13/13 [==============================] - 0s 5ms/step - loss: 7.7779 - val_loss: 28.3753
Epoch 37/100
13/13 [==============================] - 0s 5ms/step - loss: 7.8658 - val_loss: 28.5803
Epoch 38/100
13/13 [==============================] - 0s 5ms/step - loss: 8.0803 - val_loss: 27.6230
Epoch 39/100
13/13 [==============================] - 0s 5ms/step - loss: 7.3353 - val_loss: 26.9935
Epoch 40/100
13/13 [==============================] - 0s 5ms/step - loss: 7.3654 - val_loss: 27.4631
Epoch 41/100
13/13 [==============================] - 0s 4ms/step - loss: 6.9640 - val_loss: 26.8412
Epoch 42/100
13/13 [==============================] - 0s 4ms/step - loss: 6.9195 - val_loss: 26.5409
Epoch 43/100
13/13 [==============================] - 0s 5ms/step - loss: 6.8240 - val_loss: 26.9165
Epoch 44/100
13/13 [==============================] - 0s 5ms/step - loss: 6.5951 - val_loss: 24.2719
Epoch 45/100
13/13 [==============================] - 0s 6ms/step - loss: 6.4782 - val_loss: 24.9571
Epoch 46/100
13/13 [==============================] - 0s 5ms/step - loss: 6.3253 - val_loss: 23.6696
Epoch 47/100
13/13 [==============================] - 0s 5ms/step - loss: 6.1509 - val_loss: 25.9474
Epoch 48/100
13/13 [==============================] - 0s 5ms/step - loss: 6.0413 - val_loss: 24.2839
Epoch 49/100
13/13 [==============================] - 0s 5ms/step - loss: 6.0761 - val_loss: 22.3131
Epoch 50/100
13/13 [==============================] - 0s 5ms/step - loss: 5.9116 - val_loss: 24.5614
Epoch 51/100
13/13 [==============================] - 0s 5ms/step - loss: 5.6238 - val_loss: 23.0634
Epoch 52/100
13/13 [==============================] - 0s 5ms/step - loss: 5.5382 - val_loss: 23.7913
Epoch 53/100
13/13 [==============================] - 0s 5ms/step - loss: 5.5242 - val_loss: 20.1520
Epoch 54/100
13/13 [==============================] - 0s 5ms/step - loss: 5.4783 - val_loss: 26.5296
Epoch 55/100
13/13 [==============================] - 0s 4ms/step - loss: 6.0466 - val_loss: 24.1316
Epoch 56/100
13/13 [==============================] - 0s 5ms/step - loss: 5.2219 - val_loss: 22.8066
Epoch 57/100
13/13 [==============================] - 0s 5ms/step - loss: 5.1171 - val_loss: 22.3161
Epoch 58/100
13/13 [==============================] - 0s 5ms/step - loss: 4.9620 - val_loss: 21.1540
Epoch 59/100
13/13 [==============================] - 0s 5ms/step - loss: 4.9861 - val_loss: 22.9976
Epoch 60/100
13/13 [==============================] - 0s 6ms/step - loss: 4.8007 - val_loss: 22.4891
Epoch 61/100
13/13 [==============================] - 0s 5ms/step - loss: 4.8584 - val_loss: 23.6005
Epoch 62/100
13/13 [==============================] - 0s 5ms/step - loss: 4.9797 - val_loss: 21.0106
Epoch 63/100
13/13 [==============================] - 0s 5ms/step - loss: 4.4485 - val_loss: 23.1236
Epoch 64/100
13/13 [==============================] - 0s 5ms/step - loss: 4.4853 - val_loss: 21.0356
Epoch 65/100
13/13 [==============================] - 0s 5ms/step - loss: 4.3492 - val_loss: 22.1600
Epoch 66/100
13/13 [==============================] - 0s 5ms/step - loss: 4.3528 - val_loss: 21.5406
Epoch 67/100
13/13 [==============================] - 0s 5ms/step - loss: 4.3036 - val_loss: 21.0275
Epoch 68/100
13/13 [==============================] - 0s 5ms/step - loss: 4.3681 - val_loss: 21.5536
Epoch 69/100
13/13 [==============================] - 0s 5ms/step - loss: 4.2755 - val_loss: 19.6537
Epoch 70/100
13/13 [==============================] - 0s 5ms/step - loss: 4.1630 - val_loss: 21.0372
Epoch 71/100
13/13 [==============================] - 0s 5ms/step - loss: 3.9508 - val_loss: 20.4278
Epoch 72/100
13/13 [==============================] - 0s 5ms/step - loss: 4.0062 - val_loss: 17.6154
Epoch 73/100
13/13 [==============================] - 0s 5ms/step - loss: 3.9849 - val_loss: 21.1424
Epoch 74/100
13/13 [==============================] - 0s 5ms/step - loss: 3.9250 - val_loss: 21.0194
Epoch 75/100
13/13 [==============================] - 0s 5ms/step - loss: 3.7795 - val_loss: 20.1999
Epoch 76/100
13/13 [==============================] - 0s 5ms/step - loss: 4.0251 - val_loss: 19.3699
Epoch 77/100
13/13 [==============================] - 0s 5ms/step - loss: 3.6459 - val_loss: 19.6990
Epoch 78/100
13/13 [==============================] - 0s 5ms/step - loss: 3.6467 - val_loss: 18.6080
Epoch 79/100
13/13 [==============================] - 0s 5ms/step - loss: 3.6351 - val_loss: 18.8263
Epoch 80/100
13/13 [==============================] - 0s 5ms/step - loss: 3.6115 - val_loss: 19.0168
Epoch 81/100
13/13 [==============================] - 0s 5ms/step - loss: 3.4819 - val_loss: 18.3504

Epoch 82/100
13/13 [==============================] - 0s 6ms/step - loss: 3.4497 - val_loss: 17.7529
Epoch 83/100
13/13 [==============================] - 0s 5ms/step - loss: 3.4797 - val_loss: 20.9432
Epoch 84/100
13/13 [==============================] - 0s 6ms/step - loss: 3.4601 - val_loss: 16.9705
Epoch 85/100
13/13 [==============================] - 0s 6ms/step - loss: 3.3372 - val_loss: 16.5268
Epoch 86/100
13/13 [==============================] - 0s 7ms/step - loss: 3.2905 - val_loss: 17.2694
Epoch 87/100
13/13 [==============================] - 0s 5ms/step - loss: 3.1412 - val_loss: 18.2230
Epoch 88/100
13/13 [==============================] - 0s 6ms/step - loss: 3.2178 - val_loss: 19.8075
Epoch 89/100
13/13 [==============================] - 0s 7ms/step - loss: 3.2945 - val_loss: 18.7921
Epoch 90/100
13/13 [==============================] - 0s 7ms/step - loss: 3.4156 - val_loss: 17.7144
Epoch 91/100
13/13 [==============================] - 0s 6ms/step - loss: 3.0991 - val_loss: 16.7483
Epoch 92/100
13/13 [==============================] - 0s 5ms/step - loss: 3.0262 - val_loss: 17.7466
Epoch 93/100
13/13 [==============================] - 0s 5ms/step - loss: 3.4782 - val_loss: 20.3292
Epoch 94/100
13/13 [==============================] - 0s 5ms/step - loss: 3.3380 - val_loss: 18.1320
Epoch 95/100
13/13 [==============================] - 0s 5ms/step - loss: 3.1831 - val_loss: 17.0545
Epoch 96/100
13/13 [==============================] - 0s 5ms/step - loss: 3.0016 - val_loss: 16.4206
Epoch 97/100
13/13 [==============================] - 0s 5ms/step - loss: 2.8442 - val_loss: 19.5733
Epoch 98/100
13/13 [==============================] - 0s 5ms/step - loss: 3.1627 - val_loss: 15.7759
Epoch 99/100
13/13 [==============================] - 0s 5ms/step - loss: 2.9764 - val_loss: 16.1769
Epoch 100/100
13/13 [==============================] - 0s 5ms/step - loss: 2.9418 - val_loss: 17.5375

In [110]:
loss = model.evaluate(x_test,y_test)

4/4 [==============================] - 0s 3ms/step - loss: 10.2937

In [111]:
loss

10.293723106384277

In [112]:
y_pred = model.predict(x_test)

In [114]:
from sklearn.metrics import r2_score,mean_squared_error,mean_absolute_error

In [115]:
r2 = r2_score(y_test,y_pred)
r2

0.8596319342554477

In [116]:
mse = mean_squared_error(y_test,y_pred)
mse

10.293721295944957

In [118]:
y_pred = model.predict(x_test).flatten()

In [119]:
result = pd.DataFrame({'actual':y_test,'predicted':y_pred})

In [120]:
result

     actual  predicted
173    23.6  26.926725
274    32.4  32.848263
491    13.6  14.031734
72     22.8  23.446600
452    16.1  16.230125
..      ...        ...
412    17.9  10.471543
436     9.6  10.900618
411    17.2  14.450325
86     22.5  23.892633
75     21.4  21.198629

[102 rows x 2 columns]